import type { RoleDefinition, RoleId, SeniorityId } from "./types"

export const SENIORITIES: { id: SeniorityId; label: string }[] = [
  { id: "intern", label: "Intern" },
  { id: "junior", label: "Junior" },
  { id: "mid", label: "Mid-level" },
  { id: "senior", label: "Senior" },
]

export const ROLES: Record<RoleId, RoleDefinition> = {
  frontend: {
    id: "frontend",
    label: "Frontend Engineer",
    description: "Builds user-facing web interfaces with modern frameworks.",
    coreLanguages: ["TypeScript", "JavaScript", "CSS", "HTML"],
    secondaryLanguages: ["Dart", "Python", "Ruby"],
    coreTopics: ["react", "nextjs", "vue", "tailwindcss", "frontend", "ui", "web"],
    weights: { code: 0.45, dsa: 0.2, consistency: 0.2, impact: 0.15 },
    dsaBaseline: { intern: 50, junior: 100, mid: 180, senior: 280 },
    contestBaseline: { intern: null, junior: 1400, mid: 1550, senior: 1700 },
  },
  backend: {
    id: "backend",
    label: "Backend Engineer",
    description: "Designs APIs, services, and data layers that power applications.",
    coreLanguages: ["Go", "Java", "Python", "TypeScript", "Rust", "C#"],
    secondaryLanguages: ["Ruby", "Kotlin", "Scala", "C++"],
    coreTopics: ["api", "backend", "database", "microservices", "rest", "graphql", "server"],
    weights: { code: 0.4, dsa: 0.3, consistency: 0.15, impact: 0.15 },
    dsaBaseline: { intern: 70, junior: 140, mid: 240, senior: 360 },
    contestBaseline: { intern: null, junior: 1450, mid: 1600, senior: 1800 },
  },
  fullstack: {
    id: "fullstack",
    label: "Full-Stack Engineer",
    description: "Works across frontend and backend to ship complete features.",
    coreLanguages: ["TypeScript", "JavaScript", "Python", "Go"],
    secondaryLanguages: ["Java", "Ruby", "PHP", "C#"],
    coreTopics: ["react", "nextjs", "api", "database", "fullstack", "node", "web"],
    weights: { code: 0.42, dsa: 0.26, consistency: 0.17, impact: 0.15 },
    dsaBaseline: { intern: 60, junior: 120, mid: 220, senior: 330 },
    contestBaseline: { intern: null, junior: 1400, mid: 1550, senior: 1700 },
  },
  devops: {
    id: "devops",
    label: "DevOps / Platform Engineer",
    description: "Automates infrastructure, CI/CD, and cloud deployments.",
    coreLanguages: ["Go", "Python", "Shell", "HCL", "YAML"],
    secondaryLanguages: ["TypeScript", "Ruby", "Rust"],
    coreTopics: ["docker", "kubernetes", "terraform", "ci", "cd", "aws", "infrastructure", "devops"],
    weights: { code: 0.4, dsa: 0.15, consistency: 0.2, impact: 0.25 },
    dsaBaseline: { intern: 30, junior: 70, mid: 140, senior: 220 },
    contestBaseline: { intern: null, junior: null, mid: 1400, senior: 1500 },
  },
  "data-engineer": {
    id: "data-engineer",
    label: "Data Engineer",
    description: "Builds pipelines and systems that move and transform data at scale.",
    coreLanguages: ["Python", "SQL", "Scala", "Java"],
    secondaryLanguages: ["Go", "TypeScript", "Shell", "R"],
    coreTopics: ["spark", "airflow", "etl", "data", "pipeline", "sql", "warehouse", "kafka"],
    weights: { code: 0.38, dsa: 0.27, consistency: 0.15, impact: 0.2 },
    dsaBaseline: { intern: 50, junior: 110, mid: 200, senior: 300 },
    contestBaseline: { intern: null, junior: 1400, mid: 1550, senior: 1700 },
  },
  "ml-engineer": {
    id: "ml-engineer",
    label: "ML Engineer",
    description: "Develops, trains, and deploys machine learning models.",
    coreLanguages: ["Python", "C++", "Jupyter Notebook"],
    secondaryLanguages: ["Rust", "Julia", "Scala", "R"],
    coreTopics: ["pytorch", "tensorflow", "ml", "deep-learning", "nlp", "machine-learning", "ai"],
    weights: { code: 0.4, dsa: 0.3, consistency: 0.13, impact: 0.17 },
    dsaBaseline: { intern: 60, junior: 130, mid: 230, senior: 340 },
    contestBaseline: { intern: null, junior: 1450, mid: 1600, senior: 1800 },
  },
  mobile: {
    id: "mobile",
    label: "Mobile Engineer",
    description: "Builds native or cross-platform mobile applications.",
    coreLanguages: ["Swift", "Kotlin", "Dart", "TypeScript", "Java"],
    secondaryLanguages: ["Objective-C", "C++", "JavaScript"],
    coreTopics: ["ios", "android", "flutter", "react-native", "swiftui", "mobile", "kotlin"],
    weights: { code: 0.45, dsa: 0.22, consistency: 0.18, impact: 0.15 },
    dsaBaseline: { intern: 45, junior: 100, mid: 190, senior: 280 },
    contestBaseline: { intern: null, junior: 1400, mid: 1500, senior: 1650 },
  },
}

export const ROLE_LIST = Object.values(ROLES)
